// <auto-generated />
using System;
using Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030002401_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1828, 9, 9),
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1860, 1, 29),
                            Name = "Anton Chekhov"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1799, 6, 6),
                            Name = "Alexander Pushkin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublisherYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublisherYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublisherYear = 1877,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            PublisherYear = 1899,
                            Title = "Resurrection"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            PublisherYear = 1880,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            PublisherYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            PublisherYear = 1869,
                            Title = "The Idiot"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            PublisherYear = 1864,
                            Title = "Notes from Underground"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            PublisherYear = 1904,
                            Title = "The Cherry Orchard"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            PublisherYear = 1899,
                            Title = "Uncle Vanya"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            PublisherYear = 1901,
                            Title = "Three Sisters"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            PublisherYear = 1896,
                            Title = "The Seagull"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            PublisherYear = 1833,
                            Title = "Eugene Onegin"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            PublisherYear = 1825,
                            Title = "Boris Godunov"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            PublisherYear = 1836,
                            Title = "The Captain's Daughter"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 4,
                            PublisherYear = 1820,
                            Title = "Ruslan and Ludmila"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.HasOne("Domain.Entities.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
